"use client";

import Image from "next/image";

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-[#0d1117] text-[#c9d1d9] px-6 py-16">
      <div className="mx-auto max-w-4xl space-y-12">

        {/* Logo */}
        <div className="flex items-center gap-3">
          <Image
            src="/tbird-logo.png"
            alt="TbirdTrader Logo"
            width={180}
            height={40}
            priority
          />
        </div>

        {/* Home Button */}
        <div className="mt-2">
          <a
            href="/"
            className="inline-block rounded-md border border-[#30363d] px-4 py-1 text-sm text-[#c9d1d9] hover:bg-[#161b22]"
          >
            ← Home
          </a>
        </div>

        {/* Title */}
        <h1 className="text-3xl font-semibold md:text-4xl">
          Risk Disclaimer
        </h1>

        {/* Intro */}
        <p className="text-[#8b949e] text-sm md:text-base leading-relaxed">
          Trading financial assets involves significant risk. Markets can move 
          unpredictably, and past performance is never a guarantee of future results. 
          By using TbirdTrader, you acknowledge and accept these risks.
        </p>

        {/* Core Disclaimer */}
        <section className="space-y-4">
          <h2 className="text-xl font-semibold">No Financial Advice</h2>
          <p className="text-[#8b949e] text-sm md:text-base leading-relaxed">
            TbirdTrader provides tools, analytics, and automation features designed 
            to support your trading decisions. However, none of the information, 
            predictions, or signals generated by the platform should be interpreted 
            as financial advice, investment recommendations, or guarantees of 
            performance.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">No Liability for Losses</h2>
          <p className="text-[#8b949e] text-sm md:text-base leading-relaxed">
            TbirdTrader is not responsible for any financial losses, trading 
            outcomes, or damages resulting from the use of the platform. You are 
            solely responsible for your trading decisions, including any automated 
            strategies you choose to activate.
          </p>
          <p className="text-[#8b949e] text-sm md:text-base leading-relaxed">
            This includes, but is not limited to, losses caused by market volatility, 
            incorrect predictions, misinterpreted signals, or unexpected exchange 
            rate developments.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">AI Predictions Are Not Guarantees</h2>
          <p className="text-[#8b949e] text-sm md:text-base leading-relaxed">
            While TbirdTrader uses advanced algorithms and AI‑driven models, all 
            predictions are inherently uncertain. Market conditions can change 
            rapidly, and no model can guarantee accuracy or profitability.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">User Responsibility</h2>
          <p className="text-[#8b949e] text-sm md:text-base leading-relaxed">
            By using TbirdTrader, you agree that you are fully responsible for 
            evaluating the risks associated with trading and for determining whether 
            any strategy, tool, or automation feature is appropriate for your 
            financial situation.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">No Guarantees of Accuracy</h2>
          <p className="text-[#8b949e] text-sm md:text-base leading-relaxed">
            Although we strive to provide reliable tools and accurate data, 
            TbirdTrader does not guarantee the correctness, completeness, or 
            timeliness of any information displayed on the platform.
          </p>
        </section>

      </div>
    </main>
  );
}
